
# App
spring.application.name=smart-campus-api
server.port=8081

# MongoDB
spring.data.mongodb.uri=mongodb+srv://dasun:12345@smart-campus.al7xwbr.mongodb.net/smart_campus_db?retryWrites=true&w=majority
spring.data.mongodb.database=smart_campus_db

# Jackson - serialize dates as ISO strings, not arrays
spring.jackson.serialization.write-dates-as-timestamps=false

# Logging
logging.level.org.springframework=INFO
logging.level.com.smartcampus=DEBUG